# Generated by Django 3.1.3 on 2021-01-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_auto_20210116_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='order',
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='num_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store_app.order', verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
