# Generated by Django 3.1.3 on 2021-01-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_auto_20210117_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='num_order',
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store_app.order'),
            preserve_default=False,
        ),
    ]
