# Generated by Django 3.0.8 on 2020-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarynote',
            name='text',
            field=models.TextField(default='Nothing'),
        ),
    ]
