# Generated by Django 3.0.8 on 2020-07-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_diarynote_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarynote',
            old_name='note',
            new_name='note_heading',
        ),
    ]
