# Generated by Django 3.0.8 on 2020-08-05 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0004_diarynote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarynote',
            name='participants',
            field=models.ManyToManyField(related_name='note_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diarynote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
