# Generated by Django 3.0.8 on 2020-08-05 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0005_auto_20200805_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarynote',
            name='participants',
            field=models.ManyToManyField(default='', related_name='note_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
